/**
 * This file is auto generated via npm run generate.resolved-tailwind
 */
export declare type NeutralColor = "neutrals-white" | "neutrals-gray1" | "neutrals-gray2" | "neutrals-gray3" | "neutrals-gray4" | "neutrals-gray5" | "neutrals-black" | "transparent";
export declare type SignatureColor = "signature-blue1" | "signature-blue2" | "signature-blue3" | "signature-blue4" | "signature-purple1" | "signature-purple2" | "signature-purple3" | "signature-purple4" | "signature-aqua1" | "signature-aqua2" | "signature-aqua3" | "signature-aqua4" | "signature-green1" | "signature-green2" | "signature-green3" | "signature-green4";
export declare type Color = "neutrals-white" | "neutrals-gray1" | "neutrals-gray2" | "neutrals-gray3" | "neutrals-gray4" | "neutrals-gray5" | "neutrals-black" | "signature-blue1" | "signature-blue2" | "signature-blue3" | "signature-blue4" | "signature-purple1" | "signature-purple2" | "signature-purple3" | "signature-purple4" | "signature-aqua1" | "signature-aqua2" | "signature-aqua3" | "signature-aqua4" | "signature-green1" | "signature-green2" | "signature-green3" | "signature-green4" | "ui-error" | "transparent";
export declare const NEUTRAL_COLORS: NeutralColor[];
export declare const SIGNATURE_COLORS: SignatureColor[];
export declare const ALL_COLORS: Color[];
declare const _default: {
  colors: {
    neutrals: {
      white: string;
      gray1: string;
      gray2: string;
      gray3: string;
      gray4: string;
      gray5: string;
      black: string;
    };
    signature: {
      blue1: string;
      blue2: string;
      blue3: string;
      blue4: string;
      purple1: string;
      purple2: string;
      purple3: string;
      purple4: string;
      aqua1: string;
      aqua2: string;
      aqua3: string;
      aqua4: string;
      green1: string;
      green2: string;
      green3: string;
      green4: string;
    };
    ui: {
      error: string;
    };
    transparent: string;
  };
  screens: {
    sm: string;
    md: string;
    lg: string;
    xl: string;
    xxl: string;
  };
  spacing: {
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "8": string;
    "10": string;
    "12": string;
    "16": string;
    "20": string;
    "24": string;
    "32": string;
    "40": string;
    "48": string;
    "56": string;
    "64": string;
    "72": string;
    "84": string;
    "96": string;
    px: string;
  };
  backgroundColor: {
    neutrals: {
      white: string;
      gray1: string;
      gray2: string;
      gray3: string;
      gray4: string;
      gray5: string;
      black: string;
    };
    signature: {
      blue1: string;
      blue2: string;
      blue3: string;
      blue4: string;
      purple1: string;
      purple2: string;
      purple3: string;
      purple4: string;
      aqua1: string;
      aqua2: string;
      aqua3: string;
      aqua4: string;
      green1: string;
      green2: string;
      green3: string;
      green4: string;
    };
    ui: {
      error: string;
    };
    transparent: string;
  };
  backgroundImage: {
    none: string;
    "gradient-to-t": string;
    "gradient-to-tr": string;
    "gradient-to-r": string;
    "gradient-to-br": string;
    "gradient-to-b": string;
    "gradient-to-bl": string;
    "gradient-to-l": string;
    "gradient-to-tl": string;
    "rainbow-gradient-x": string;
    "rainbow-gradient-y": string;
  };
  gradientColorStops: {
    neutrals: {
      white: string;
      gray1: string;
      gray2: string;
      gray3: string;
      gray4: string;
      gray5: string;
      black: string;
    };
    signature: {
      blue1: string;
      blue2: string;
      blue3: string;
      blue4: string;
      purple1: string;
      purple2: string;
      purple3: string;
      purple4: string;
      aqua1: string;
      aqua2: string;
      aqua3: string;
      aqua4: string;
      green1: string;
      green2: string;
      green3: string;
      green4: string;
    };
    ui: {
      error: string;
    };
    transparent: string;
  };
  backgroundOpacity: {
    "0": string;
    "25": string;
    "40": string;
    "50": string;
    "75": string;
    "100": string;
  };
  backgroundPosition: {
    bottom: string;
    center: string;
    left: string;
    "left-bottom": string;
    "left-top": string;
    right: string;
    "right-bottom": string;
    "right-top": string;
    top: string;
  };
  backgroundSize: {
    auto: string;
    cover: string;
    contain: string;
  };
  borderColor: {
    neutrals: {
      white: string;
      gray1: string;
      gray2: string;
      gray3: string;
      gray4: string;
      gray5: string;
      black: string;
    };
    signature: {
      blue1: string;
      blue2: string;
      blue3: string;
      blue4: string;
      purple1: string;
      purple2: string;
      purple3: string;
      purple4: string;
      aqua1: string;
      aqua2: string;
      aqua3: string;
      aqua4: string;
      green1: string;
      green2: string;
      green3: string;
      green4: string;
    };
    ui: {
      error: string;
    };
    transparent: string;
    default: string;
  };
  borderOpacity: {
    "0": string;
    "25": string;
    "40": string;
    "50": string;
    "75": string;
    "100": string;
  };
  borderRadius: {
    none: string;
    sm: string;
    default: string;
    md: string;
    lg: string;
    xl: string;
    "2xl": string;
    "3xl": string;
    full: string;
  };
  borderWidth: {
    "0": string;
    "2": string;
    "4": string;
    "8": string;
    default: string;
  };
  boxShadow: {
    xs: string;
    sm: string;
    default: string;
    md: string;
    lg: string;
    xl: string;
    "2xl": string;
    inner: string;
    outline: string;
    none: string;
    "aes-lg": string;
    focus: string;
    "focus-2": string;
    "focus-error": string;
  };
  container: {};
  cursor: {
    auto: string;
    default: string;
    pointer: string;
    wait: string;
    text: string;
    move: string;
    "not-allowed": string;
  };
  divideColor: {
    neutrals: {
      white: string;
      gray1: string;
      gray2: string;
      gray3: string;
      gray4: string;
      gray5: string;
      black: string;
    };
    signature: {
      blue1: string;
      blue2: string;
      blue3: string;
      blue4: string;
      purple1: string;
      purple2: string;
      purple3: string;
      purple4: string;
      aqua1: string;
      aqua2: string;
      aqua3: string;
      aqua4: string;
      green1: string;
      green2: string;
      green3: string;
      green4: string;
    };
    ui: {
      error: string;
    };
    transparent: string;
    default: string;
  };
  divideOpacity: {
    "0": string;
    "25": string;
    "40": string;
    "50": string;
    "75": string;
    "100": string;
  };
  divideWidth: {
    "0": string;
    "2": string;
    "4": string;
    "8": string;
    default: string;
  };
  fill: {
    current: string;
  };
  flex: {
    "1": string;
    auto: string;
    initial: string;
    none: string;
  };
  flexGrow: {
    "0": string;
    default: string;
  };
  flexShrink: {
    "0": string;
    default: string;
  };
  fontFamily: {
    sans: string[];
    serif: string[];
    mono: string[];
    display: string[];
    body: string[];
  };
  fontSize: {
    xs: string;
    sm: string;
    base: string;
    lg: string;
    xl: string;
    "2xl": string;
    "3xl": string;
    "4xl": string;
    "5xl": string;
    "6xl": string;
    "7xl": string;
    "8xl": string;
  };
  fontWeight: {
    hairline: string;
    thin: string;
    light: string;
    normal: string;
    medium: string;
    semibold: string;
    bold: string;
    extrabold: string;
    black: string;
  };
  height: {
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "8": string;
    "10": string;
    "12": string;
    "16": string;
    "20": string;
    "24": string;
    "32": string;
    "40": string;
    "48": string;
    "56": string;
    "64": string;
    "72": string;
    "84": string;
    "96": string;
    auto: string;
    px: string;
    full: string;
    screen: string;
    "full-screen-w": string;
    "half-screen-w": string;
    "quarter-screen-w": string;
    "full-screen-h": string;
    "half-screen-h": string;
    "quarter-screen-h": string;
  };
  inset: {
    "0": string;
    auto: string;
  };
  letterSpacing: {
    tighter: string;
    tight: string;
    normal: string;
    wide: string;
    wider: string;
    widest: string;
  };
  lineHeight: {
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "7": string;
    "8": string;
    "9": string;
    "10": string;
    none: string;
    tight: string;
    snug: string;
    normal: string;
    relaxed: string;
    loose: string;
  };
  listStyleType: {
    none: string;
    disc: string;
    decimal: string;
  };
  margin: {
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "8": string;
    "10": string;
    "12": string;
    "16": string;
    "20": string;
    "24": string;
    "32": string;
    "40": string;
    "48": string;
    "56": string;
    "64": string;
    "72": string;
    "84": string;
    "96": string;
    auto: string;
    px: string;
    "-1": string;
    "-2": string;
    "-3": string;
    "-4": string;
    "-5": string;
    "-6": string;
    "-8": string;
    "-10": string;
    "-12": string;
    "-16": string;
    "-20": string;
    "-24": string;
    "-32": string;
    "-40": string;
    "-48": string;
    "-56": string;
    "-64": string;
    "-72": string;
    "-84": string;
    "-96": string;
    "-px": string;
  };
  maxHeight: {
    full: string;
    screen: string;
    "full-screen-w": string;
    "half-screen-w": string;
    "quarter-screen-w": string;
    "full-screen-h": string;
    "half-screen-h": string;
    "quarter-screen-h": string;
  };
  maxWidth: {
    none: string;
    xs: string;
    sm: string;
    md: string;
    lg: string;
    xl: string;
    "2xl": string;
    "3xl": string;
    "4xl": string;
    "5xl": string;
    "6xl": string;
    full: string;
    "screen-sm": string;
    "screen-md": string;
    "screen-lg": string;
    "screen-xl": string;
    "screen-xxl": string;
    "full-screen-w": string;
    "half-screen-w": string;
    "quarter-screen-w": string;
    "full-screen-h": string;
    "half-screen-h": string;
    "quarter-screen-h": string;
  };
  minHeight: {
    "0": string;
    full: string;
    screen: string;
  };
  minWidth: {
    "0": string;
    full: string;
  };
  objectPosition: {
    bottom: string;
    center: string;
    left: string;
    "left-bottom": string;
    "left-top": string;
    right: string;
    "right-bottom": string;
    "right-top": string;
    top: string;
  };
  opacity: {
    "0": string;
    "25": string;
    "40": string;
    "50": string;
    "75": string;
    "100": string;
  };
  order: {
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "7": string;
    "8": string;
    "9": string;
    "10": string;
    "11": string;
    "12": string;
    first: string;
    last: string;
    none: string;
  };
  outline: {
    none: string[];
    white: string[];
    black: string[];
  };
  padding: {
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "8": string;
    "10": string;
    "12": string;
    "16": string;
    "20": string;
    "24": string;
    "32": string;
    "40": string;
    "48": string;
    "56": string;
    "64": string;
    "72": string;
    "84": string;
    "96": string;
    px: string;
  };
  placeholderColor: {
    neutrals: {
      white: string;
      gray1: string;
      gray2: string;
      gray3: string;
      gray4: string;
      gray5: string;
      black: string;
    };
    signature: {
      blue1: string;
      blue2: string;
      blue3: string;
      blue4: string;
      purple1: string;
      purple2: string;
      purple3: string;
      purple4: string;
      aqua1: string;
      aqua2: string;
      aqua3: string;
      aqua4: string;
      green1: string;
      green2: string;
      green3: string;
      green4: string;
    };
    ui: {
      error: string;
    };
    transparent: string;
  };
  placeholderOpacity: {
    "0": string;
    "25": string;
    "40": string;
    "50": string;
    "75": string;
    "100": string;
  };
  space: {
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "8": string;
    "10": string;
    "12": string;
    "16": string;
    "20": string;
    "24": string;
    "32": string;
    "40": string;
    "48": string;
    "56": string;
    "64": string;
    "72": string;
    "84": string;
    "96": string;
    px: string;
    "-1": string;
    "-2": string;
    "-3": string;
    "-4": string;
    "-5": string;
    "-6": string;
    "-8": string;
    "-10": string;
    "-12": string;
    "-16": string;
    "-20": string;
    "-24": string;
    "-32": string;
    "-40": string;
    "-48": string;
    "-56": string;
    "-64": string;
    "-72": string;
    "-84": string;
    "-96": string;
    "-px": string;
  };
  stroke: {
    current: string;
  };
  strokeWidth: {
    "0": string;
    "1": string;
    "2": string;
  };
  textColor: {
    neutrals: {
      white: string;
      gray1: string;
      gray2: string;
      gray3: string;
      gray4: string;
      gray5: string;
      black: string;
    };
    signature: {
      blue1: string;
      blue2: string;
      blue3: string;
      blue4: string;
      purple1: string;
      purple2: string;
      purple3: string;
      purple4: string;
      aqua1: string;
      aqua2: string;
      aqua3: string;
      aqua4: string;
      green1: string;
      green2: string;
      green3: string;
      green4: string;
    };
    ui: {
      error: string;
    };
    transparent: string;
  };
  textOpacity: {
    "0": string;
    "25": string;
    "40": string;
    "50": string;
    "75": string;
    "100": string;
  };
  width: {
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "8": string;
    "10": string;
    "12": string;
    "16": string;
    "20": string;
    "24": string;
    "32": string;
    "40": string;
    "48": string;
    "56": string;
    "64": string;
    "72": string;
    "84": string;
    "96": string;
    auto: string;
    px: string;
    "1/2": string;
    "1/3": string;
    "2/3": string;
    "1/4": string;
    "2/4": string;
    "3/4": string;
    "1/5": string;
    "2/5": string;
    "3/5": string;
    "4/5": string;
    "1/6": string;
    "2/6": string;
    "3/6": string;
    "4/6": string;
    "5/6": string;
    "1/12": string;
    "2/12": string;
    "3/12": string;
    "4/12": string;
    "5/12": string;
    "6/12": string;
    "7/12": string;
    "8/12": string;
    "9/12": string;
    "10/12": string;
    "11/12": string;
    full: string;
    screen: string;
    "full-screen-w": string;
    "half-screen-w": string;
    "quarter-screen-w": string;
    "full-screen-h": string;
    "half-screen-h": string;
    "quarter-screen-h": string;
  };
  zIndex: {
    "0": string;
    "10": string;
    "20": string;
    "30": string;
    "40": string;
    "50": string;
    auto: string;
  };
  gap: {
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "8": string;
    "10": string;
    "12": string;
    "16": string;
    "20": string;
    "24": string;
    "32": string;
    "40": string;
    "48": string;
    "56": string;
    "64": string;
    "72": string;
    "84": string;
    "96": string;
    px: string;
  };
  gridTemplateColumns: {
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "7": string;
    "8": string;
    "9": string;
    "10": string;
    "11": string;
    "12": string;
    none: string;
    "1-2": string;
    "2-1": string;
  };
  gridAutoColumns: {
    auto: string;
    min: string;
    max: string;
    fr: string;
  };
  gridColumn: {
    auto: string;
    "span-1": string;
    "span-2": string;
    "span-3": string;
    "span-4": string;
    "span-5": string;
    "span-6": string;
    "span-7": string;
    "span-8": string;
    "span-9": string;
    "span-10": string;
    "span-11": string;
    "span-12": string;
    "span-full": string;
  };
  gridColumnStart: {
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "7": string;
    "8": string;
    "9": string;
    "10": string;
    "11": string;
    "12": string;
    "13": string;
    auto: string;
  };
  gridColumnEnd: {
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "7": string;
    "8": string;
    "9": string;
    "10": string;
    "11": string;
    "12": string;
    "13": string;
    auto: string;
  };
  gridTemplateRows: {
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    none: string;
  };
  gridAutoRows: {
    auto: string;
    min: string;
    max: string;
    fr: string;
  };
  gridRow: {
    auto: string;
    "span-1": string;
    "span-2": string;
    "span-3": string;
    "span-4": string;
    "span-5": string;
    "span-6": string;
    "span-full": string;
  };
  gridRowStart: {
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "7": string;
    auto: string;
  };
  gridRowEnd: {
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "7": string;
    auto: string;
  };
  transformOrigin: {
    center: string;
    top: string;
    "top-right": string;
    right: string;
    "bottom-right": string;
    bottom: string;
    "bottom-left": string;
    left: string;
    "top-left": string;
  };
  scale: {
    "0": string;
    "50": string;
    "75": string;
    "90": string;
    "95": string;
    "100": string;
    "105": string;
    "110": string;
    "125": string;
    "150": string;
  };
  rotate: {
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "6": string;
    "12": string;
    "45": string;
    "90": string;
    "180": string;
    "-180": string;
    "-90": string;
    "-45": string;
    "-12": string;
    "-6": string;
    "-3": string;
    "-2": string;
    "-1": string;
  };
  translate: {
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "4": string;
    "5": string;
    "6": string;
    "8": string;
    "10": string;
    "12": string;
    "16": string;
    "20": string;
    "24": string;
    "32": string;
    "40": string;
    "48": string;
    "56": string;
    "64": string;
    "72": string;
    "84": string;
    "96": string;
    px: string;
    "-1": string;
    "-2": string;
    "-3": string;
    "-4": string;
    "-5": string;
    "-6": string;
    "-8": string;
    "-10": string;
    "-12": string;
    "-16": string;
    "-20": string;
    "-24": string;
    "-32": string;
    "-40": string;
    "-48": string;
    "-56": string;
    "-64": string;
    "-72": string;
    "-84": string;
    "-96": string;
    "-px": string;
    "-full": string;
    "-1/2": string;
    "1/2": string;
    full: string;
  };
  skew: {
    "0": string;
    "1": string;
    "2": string;
    "3": string;
    "6": string;
    "12": string;
    "-12": string;
    "-6": string;
    "-3": string;
    "-2": string;
    "-1": string;
  };
  transitionProperty: {
    none: string;
    all: string;
    default: string;
    colors: string;
    opacity: string;
    shadow: string;
    transform: string;
  };
  transitionTimingFunction: {
    linear: string;
    in: string;
    out: string;
    "in-out": string;
  };
  transitionDuration: {
    "75": string;
    "100": string;
    "150": string;
    "200": string;
    "300": string;
    "500": string;
    "700": string;
    "1000": string;
  };
  transitionDelay: {
    "75": string;
    "100": string;
    "150": string;
    "200": string;
    "300": string;
    "500": string;
    "700": string;
    "1000": string;
  };
  animation: {
    none: string;
    spin: string;
    ping: string;
    pulse: string;
    bounce: string;
  };
  keyframes: {
    spin: {
      to: {
        transform: string;
      };
    };
    ping: {
      "75%, 100%": {
        transform: string;
        opacity: string;
      };
    };
    pulse: {
      "50%": {
        opacity: string;
      };
    };
    bounce: {
      "0%, 100%": {
        transform: string;
        animationTimingFunction: string;
      };
      "50%": {
        transform: string;
        animationTimingFunction: string;
      };
    };
  };
};
export default _default;
