#!/usr/bin/env bash
## Update current branch from upstream branch.
## Runs outside the container.

source "$(dirname $0)/../.helper"

set -e

# Save the current branch name.
currentBranch=$(current_branch)
parentBranch=$($(dirname $0)/parent)

# See if we need to stash changes.
doStash=0
if [[ $(git diff --stat --ignore-submodules) != '' ]]; then
  doStash=1
fi

# Now update the current branch from its parent.
if [ $doStash -eq 1 ]; then
  echo_exec git stash push
fi
echo_exec git fetch

if [ "$currentBranch" == "$parentBranch" ]; then
  echo_exec git pull
else
  echo_exec git merge --no-ff -m "chore: updating '${currentBranch}' from '${parentBranch}'" origin/${parentBranch}
fi

if [ ! -z "$(git submodule)" ]; then
  echo_exec git submodule sync
  echo_exec git submodule update --remote --merge
fi

if [ $doStash -eq 1 ]; then
  echo_exec git stash pop -q
fi
