<?php

/**
 * @file
 * Conatins hover_effects.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function slick_carousel_slider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.slick_carousel_slider':
      return t('Integarating Slick plugin to Drupal.');
  }
}

/**
 * Implements hook_page_attachments().
 */
function slick_carousel_slider_page_attachments(&$page) {
  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    $page['#attached']['library'][] = 'slick_carousel_slider/slick';
  }
}
