/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface MainCard {
        "colorClass": string;
        "heading": string;
        "subHeading": string;
    }
    interface OurFeatures {
    }
}
declare global {
    interface HTMLMainCardElement extends Components.MainCard, HTMLStencilElement {
    }
    var HTMLMainCardElement: {
        prototype: HTMLMainCardElement;
        new (): HTMLMainCardElement;
    };
    interface HTMLOurFeaturesElement extends Components.OurFeatures, HTMLStencilElement {
    }
    var HTMLOurFeaturesElement: {
        prototype: HTMLOurFeaturesElement;
        new (): HTMLOurFeaturesElement;
    };
    interface HTMLElementTagNameMap {
        "main-card": HTMLMainCardElement;
        "our-features": HTMLOurFeaturesElement;
    }
}
declare namespace LocalJSX {
    interface MainCard {
        "colorClass"?: string;
        "heading"?: string;
        "subHeading"?: string;
    }
    interface OurFeatures {
    }
    interface IntrinsicElements {
        "main-card": MainCard;
        "our-features": OurFeatures;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "main-card": LocalJSX.MainCard & JSXBase.HTMLAttributes<HTMLMainCardElement>;
            "our-features": LocalJSX.OurFeatures & JSXBase.HTMLAttributes<HTMLOurFeaturesElement>;
        }
    }
}
